Check for root in instack-virt-setup
A lot of people seem to be accidentally running this as root, and
it will eventually fail copying ssh keys when that happens.  Add
an explicit check to the top of the script to catch that right away
and provide a clear error message.

Change-Id: Ia4cd555d7cb91d415b37404b20aa31e71eb1a0a1

diff --git a/scripts/instack-virt-setup b/scripts/instack-virt-setup
--- a/scripts/instack-virt-setup
+++ b/scripts/instack-virt-setup
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ $EUID -eq 0 ]; then
+    echo "This script cannot be run as root."
+    exit 1
+fi
+
 set -ex
 
 export LIBVIRT_DEFAULT_URI="qemu:///system"
