instack-prepare-for-overcloud should also download vmlinuz/initrd files if they exist

diff --git a/scripts/instack-prepare-for-overcloud b/scripts/instack-prepare-for-overcloud
--- a/scripts/instack-prepare-for-overcloud
+++ b/scripts/instack-prepare-for-overcloud
@@ -25,6 +25,16 @@ function download_image {
     if [ ! -f $image_name ]; then
         curl -L -O $IMG_SOURCE_URL/$image_name
     fi
+
+    # Allow the download to fail, in case initrd/vmlinuz is not available,
+    # will fall back to old behavior of extraction via
+    # disk-image-get-kernel
+    for f in vmlinuz initrd; do
+        local file_name=$(basename -s .qcow2 $image_name).$f
+        if [ ! -f $file_name ]; then
+            curl -L -O $IMG_SOURCE_URL/$file_name || true
+        fi
+    done
 }
 
 function load_image {
